changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Performance
      labels:
        - performance
    - title: Dependencies
      labels:
        - dependency
    - title: Documentation
      labels:
        - documentation
    - title: CI/CD
      labels:
        - ci
    - title: Refactoring
      labels:
        - refactor
    - title: Tests
      labels:
        - tests
    - title: Other Changes
      labels:
        - "*"
